import * as cdk           from 'aws-cdk-lib';
import * as s3            from 'aws-cdk-lib/aws-s3';
import * as s3deploy      from 'aws-cdk-lib/aws-s3-deployment';
import * as cloudfront    from 'aws-cdk-lib/aws-cloudfront';
import * as origins       from 'aws-cdk-lib/aws-cloudfront-origins';
import * as path          from 'path';
import * as fs            from 'fs';
import { Construct }      from 'constructs';

interface FrontendStackProps extends cdk.StackProps {
  apiUrl:            string;
  userPoolId:        string;
  userPoolClientId:  string;
}

export class FrontendStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: FrontendStackProps) {
    super(scope, id, props);
    const { apiUrl, userPoolId, userPoolClientId } = props;

    // ── S3 bucket for SPA files ───────────────────────────────────
    const spaBucket = new s3.Bucket(this, 'SpaBucket', {
      bucketName:        `parking-frontend-${this.account}-${this.region}`,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      removalPolicy:     cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    // ── CloudFront distribution ───────────────────────────────────
    const oac = new cloudfront.S3OriginAccessControl(this, 'OAC', {
      description: 'Parking residential SPA',
    });

    const distribution = new cloudfront.Distribution(this, 'Distribution', {
      defaultBehavior: {
        origin: origins.S3BucketOrigin.withOriginAccessControl(spaBucket, { originAccessControl: oac }),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        cachePolicy:          cloudfront.CachePolicy.CACHING_OPTIMIZED,
      },
      defaultRootObject: 'index.html',
      // SPA routing: all 4xx → index.html (hash router handles the rest)
      errorResponses: [
        { httpStatus: 403, responseHttpStatus: 200, responsePagePath: '/index.html', ttl: cdk.Duration.seconds(0) },
        { httpStatus: 404, responseHttpStatus: 200, responsePagePath: '/index.html', ttl: cdk.Duration.seconds(0) },
      ],
      priceClass: cloudfront.PriceClass.PRICE_CLASS_100,  // US + EU only — cheapest
    });

    // ── Write env.js so the SPA knows where to call ───────────────
    // This file is generated at synth time and deployed with the SPA
    const envJsContent = `// Auto-generated by CDK — do not edit manually
window.__ENV = {
  API_URL:            '${apiUrl}',
  COGNITO_USER_POOL:  '${userPoolId}',
  COGNITO_CLIENT_ID:  '${userPoolClientId}',
  REGION:             '${this.region}',
};
`;

    const frontendDir = path.join(__dirname, '../../../frontend');
    const envJsPath   = path.join(frontendDir, 'js/config/env.js');
    fs.writeFileSync(envJsPath, envJsContent);

    // ── Deploy frontend to S3 ─────────────────────────────────────
    new s3deploy.BucketDeployment(this, 'DeployFrontend', {
      sources:          [s3deploy.Source.asset(frontendDir)],
      destinationBucket: spaBucket,
      distribution,
      distributionPaths: ['/*'],    // invalidate CloudFront cache on every deploy
    });

    new cdk.CfnOutput(this, 'CloudFrontUrl', { value: `https://${distribution.distributionDomainName}`, exportName: 'ParkingAppUrl' });
    new cdk.CfnOutput(this, 'DistributionId', { value: distribution.distributionId });
  }
}
